export default function Head() {
  return (
    <>
      <title>
        Tic Tac Toe | Frontend challenge from frontendmentor.io done by Dominik
        Rubröder
      </title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
